In [249]:
%matplotlib inline

from sklearn import datasets
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#関数の引数を調べる
import inspect
#inspect.signature(f)
#バージョンの確認
from distutils.version import LooseVersion as Version
from sklearn import __version__ as sklearn_version
#Version(sklearn_version)

In [250]:
import pyprind

In [254]:
import sys
sys.getdefaultencoding()

'utf-8'

In [ ]:
pbar = pyprind.ProgBar(50000)
labels = {'pos':1, 'neg': 0}
df = pd.DataFrame()
basepath = '/Users/keeeeei/Downloads/aclImdb'
for s in ('test', 'train'):
    for l in ('pos', 'neg'):
        #os.path.joinはパスの要素をうまく結合する
        path = os.path.join(basepath,s,l)
        #os.listdirは指定したパス内のファイル全てのリストを返す
        for file in os.listdir(path):
            #openでそのファイルを開く　withを使うとファイルのclose()を書き忘れることがない
            #rは書き込みモード
            #ファイルを作成する場合は、ファイルを書き込みモード w あるいは追加書き込みモード a で開く。
            #書き込みモードで開くとき、ファイルが既に存在している場合はその内容が破棄される。
            #追加書き込みモードでは、既存のファイルの下側に、内容を追加する。
            with open(os.path.join(path, file), 'r', encoding='utf-8') as infile:
                txt = infile.read()
                df = df.append([[txt, labels[l]]], ignore_index=True)
                pbar.update()

In [14]:
# 指定した場合は指定フォルダのリストを返す
os.listdir('/Users/keeeeei/Desktop')


['.DS_Store',
 '.localized',
 '.Rapp.history',
 '.Rhistory',
 '2015分配率宣伝費執行状況検証表.xlsx',
 'Clipbox',
 'IMG_0603.jpg',
 'IMG_0686.jpg',
 'IMG_1262.jpg',
 'IMG_1318.jpg',
 'IMG_1548.jpg',
 'IMG_1568.jpg',
 'IMG_1575.jpg',
 'IMG_1583.jpg',
 'IMG_1606.jpg',
 'IMG_1729.jpg',
 'IMG_1738.jpg',
 'IMG_1749.jpg',
 'IMG_2528.jpg',
 'IMG_2543.jpg',
 'IMG_2592.jpg',
 'IMG_2618.jpg',
 'IMG_2775 (1).jpg',
 'IMG_3331.jpg',
 'IMG_3403.jpg',
 'ipaexg00301',
 'Launcher.app',
 'Tutorial',
 'UFO',
 'Untitled.dmg',
 'XGboost_3.txt',
 'スクショ',
 'ゼミ課題',
 'データ分析',
 'プレゼン.pptx',
 '一人暮らし試算.xlsx',
 '名称未設定.png',
 '夏休みの一週間のうちに最低限やることリスト.xlsx',
 '就活',
 '履修.xlsx',
 '講義']

In [11]:
os.getcwd()

'/Users/keeeeei/Desktop/データ分析/Python機械学習プログラミング'

In [15]:
#str()関数は引数で与えた値を人間が読みやすい文字列
s = 'Hello, world.'
str(s)

'Hello, world.'

In [16]:
#reprは引数で与えた値と等価な値を返すインタプリタ表現（リテラル表記）を文字列として返す
repr(s)

"'Hello, world.'"

In [40]:
with open(os.path.join(os.getcwd(), 'sample.csv'), 'r', encoding='utf-8') as infile:
    txt = infile.read()

In [41]:
txt

'id,jan\n001,a\n002,b\n003,c\n004,d\n005,e\n006,f\n007,g\n008,h\n009,i\n010,j\n011,k'

In [158]:
df.columns = ['review', 'sentiment']

In [159]:
df.head()

review  sentiment
0  I went and saw this movie last night after bei...          1
1  Actor turned director Bill Paxton follows up h...          1
2  As a recreational golfer with some knowledge o...          1
3  I saw this film in a sneak preview, and it is ...          1
4  Bill Paxton has taken the true story of the 19...          1

In [63]:
df.sentiment.value_counts()

1    25000
0    25000
Name: sentiment, dtype: int64

In [42]:
##データをシャッフルしてCSVで保存
np.random.seed(0)
df = df.reindex(np.random.permutation(df.index))
df.to_csv('movie_data.csv',index=False)

In [43]:
iris = datasets.load_iris()
X, y = iris.data[50:, [1,2]], iris.target[50:]

In [46]:
X = pd.DataFrame(X)

In [207]:
X.head()

0    1
0  3.2  4.7
1  3.2  4.5
2  3.1  4.9
3  2.3  4.0
4  2.8  4.6

In [52]:
X.reindex(np.random.permutation(X.index)).head()

0    1
25  3.0  4.4
79  3.0  5.8
53  2.9  5.6
99  3.0  5.1
69  2.2  5.0

In [160]:
df = pd.read_csv('movie_data.csv')
df.head()

review  sentiment
0  In 1974, the teenager Martha Moxley (Maggie Gr...          1
1  OK... so... I really like Kris Kristofferson a...          0
2  ***SPOILER*** Do not read this, if you think a...          0
3  hi for all the people who have seen this wonde...          1
4  I recently bought the DVD, forgetting just how...          0

In [59]:
##単語を特徴ベクトルに変換する
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer()
docs = np.array(['The sun is shining', 'The weather is sweet', 'The sun is shining, the weather is sweet, and one and one is two'])
bag = count.fit_transform(docs)

In [60]:
print(count.vocabulary_)

{'the': 6, 'and': 0, 'two': 7, 'one': 2, 'is': 1, 'weather': 8, 'shining': 3, 'sun': 4, 'sweet': 5}


In [61]:
#特徴ベクトル
#列が上の辞書の整数値に対応
print(bag.toarray())

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]


In [65]:
bag

<3x9 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [62]:
print(count.get_feature_names())

['and', 'is', 'one', 'shining', 'sun', 'sweet', 'the', 'two', 'weather']


In [66]:
#TF-IDFを使って単語の関連性を評価する
from sklearn.feature_extraction.text import TfidfTransformer
#use_idfはidfを使うかどうか(使わないと単にtfを出力)
#smooth_idfはIDFの計算式の分子と分母に1を加える　→分母が０にならないためなどの理由
tfidf = TfidfTransformer(use_idf=True, norm='l2', smooth_idf=True)
np.set_printoptions(precision=2)
print(tfidf.fit_transform(bag).toarray())

[[ 0.    0.43  0.    0.56  0.56  0.    0.43  0.    0.  ]
 [ 0.    0.43  0.    0.    0.    0.56  0.43  0.    0.56]
 [ 0.5   0.45  0.5   0.19  0.19  0.19  0.3   0.25  0.19]]


In [68]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(use_idf=True, norm='l2', smooth_idf=True)
print(tfidf.fit_transform(docs).toarray())

[[ 0.    0.43  0.    0.56  0.56  0.    0.43  0.    0.  ]
 [ 0.    0.43  0.    0.    0.    0.56  0.43  0.    0.56]
 [ 0.5   0.45  0.5   0.19  0.19  0.19  0.3   0.25  0.19]]


テキストデータのクレンジング

In [174]:
df.loc[0, 'review'][-50:]

'is seven.<br /><br />Title (Brazil): Not Available'

In [71]:
df.loc[0, 'review']

'In 1974, the teenager Martha Moxley (Maggie Grace) moves to the high-class area of Belle Haven, Greenwich, Connecticut. On the Mischief Night, eve of Halloween, she was murdered in the backyard of her house and her murder remained unsolved. Twenty-two years later, the writer Mark Fuhrman (Christopher Meloni), who is a former LA detective that has fallen in disgrace for perjury in O.J. Simpson trial and moved to Idaho, decides to investigate the case with his partner Stephen Weeks (Andrew Mitchell) with the purpose of writing a book. The locals squirm and do not welcome them, but with the support of the retired detective Steve Carroll (Robert Forster) that was in charge of the investigation in the 70\'s, they discover the criminal and a net of power and money to cover the murder.<br /><br />"Murder in Greenwich" is a good TV movie, with the true story of a murder of a fifteen years old girl that was committed by a wealthy teenager whose mother was a Kennedy. The powerful and rich famil

正規表現

In [148]:
import re
def preprocessor(text):
    #sub(pattern, repl, string)正規表現にマッチする部分をreplにある文字に置き換えます
    #findall(pattern, string)正規表現にマッチする部分文字列を全て探しだしリストとして返します。
    #[]は文字の集合を表す、[]内の最初の文字が^の場合は集合にない文字にマッチする
    #'<[^>]*>'　の正規表現の部分は[^>]*である
    #[^>]で>以外の全ての文字列にマッチ
    #*で[^>]を可能な限り繰り返す
    #そして最後が>で終わるものを削除したものを返す
    text = re.sub('<[^>]*>','', text)
    #?は直前の正規表現が0か1回使われているとマッチ
    #()はその中に含まれた表現をまとめてグループ化する
    #(?:)はグループ化はするけどその個々のグループの結果の内容は保存しないもの(メモリの節約)
    #'(?::|;|=)(?:-)?(?:\)|\(|D|P)' は分かりやすく書くと(?:  :|;|=　)  (?:  -)?   (?:  \)|\(|D|P    )
    #()は式集合であり、パターンをグループ化したもの
    #[]は文字集合であり、中身は必ず文字
    emotions = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)',text)
    #\W は任意の非英数文字とマッチします; これは集合 [^a-zA-Z0-9_] と同じ意味です。
    #''x'.join(list)でxを区切り文字としてlistの要素を連結した文字列を返す
    text = re.sub('[\W]+', ' ', text.lower()) + ' '.join(emotions).replace('-', '')
    return text

In [94]:
re.sub('a[bcd]*b', '', 'abbd afffb abcdb')

'd afffb '

In [80]:
import re
p = re.compile('a[bcd]*b')

In [91]:
print(p.match('afffb abcdb').group())

AttributeError: 'NoneType' object has no attribute 'group'

In [90]:
print(p.search(' afffb abcdb').group())

abcdb


In [93]:
print(p.findall('abbd afffb abcdb'))

['abb', 'abcdb']


In [120]:
p = re.compile('([ab])+')
m = p.match('ab')
print(m.group())
print(m.group(0))
print(m.group(1))
print(m.groups())

ab
ab
b
('b',)


In [113]:
#groups() メソッドは 1 から全てのサブグループの文字列を含むタプルを返します。
m = re.match("([abc])+", "abc")
m.groups()

('c',)

In [130]:
p = re.compile('(a)b')
m = p.match('abc')
print(m.group())
print(m.group(0))
print(m.group(1))
print(m.groups())

ab
ab
a
('a',)


In [129]:
p = re.compile('([ab])+')
m = p.match('abc')
print(m.group())
print(m.group(0))
print(m.group(1))
print(m.groups())

ab
ab
b
('b',)


In [140]:
p = re.compile('(?:[ab]*)')
m = p.match('abc')
print(m.group())
print(m.group(0))
print(m.group(1))
print(m.groups())

ab
ab


IndexError: no such group

In [179]:
p = re.compile('[ab]*')
m = p.match('abc')
print(m.group())
print(m.group(0))
print(m.groups())

ab
ab
()


In [202]:
p = re.compile("(a[^>]*)c")
m = p.match('abbbbbc')
print(m.group())
print(m.group(0))
print(m.group(1))
print(m.groups())

abbbbbc
abbbbbc
abbbbb
('abbbbb',)


In [149]:
preprocessor(df.loc[0, 'review'][-50:])

'is seven title brazil not available'

In [150]:
preprocessor("</a>This :) is :(  a test :-)!")

'this is a test :) :( :)'

In [175]:
df['review'] = df['review'].apply(preprocessor)

In [162]:
df1 = pd.DataFrame()
df1['review'] = df['review'].apply(preprocessor)

In [163]:
df1.loc[0, 'review']

'in 1974 the teenager martha moxley maggie grace moves to the high class area of belle haven greenwich connecticut on the mischief night eve of halloween she was murdered in the backyard of her house and her murder remained unsolved twenty two years later the writer mark fuhrman christopher meloni who is a former la detective that has fallen in disgrace for perjury in o j simpson trial and moved to idaho decides to investigate the case with his partner stephen weeks andrew mitchell with the purpose of writing a book the locals squirm and do not welcome them but with the support of the retired detective steve carroll robert forster that was in charge of the investigation in the 70 s they discover the criminal and a net of power and money to cover the murder murder in greenwich is a good tv movie with the true story of a murder of a fifteen years old girl that was committed by a wealthy teenager whose mother was a kennedy the powerful and rich family used their influence to cover the mur

(?:)は[]で代替可能か →　今回は可能だった！！ 

# ()には正規表現自体を入れることができるのが違い　\1とかも使える！
\1 はグループ1の内容が現在位置で見つかった場合成功し、それ以外の場合に失敗します。

In [151]:
import re
def preprocessor1(text):
    text = re.sub('<[^>]*>','', text)
    emotions = re.findall('[:;=][-]?[)(DP]',text)
    text = re.sub('[\W]+', ' ', text.lower()) + ' '.join(emotions).replace('-', '')
    return text

In [152]:
preprocessor1(df.loc[0, 'review'][-50:])

'is seven title brazil not available'

In [153]:
preprocessor1("</a>This :) is :(  a test :-)!")

'this is a test :) :( :)'

In [164]:
df2 = pd.DataFrame()
df2['review'] = df['review'].apply(preprocessor1)

In [176]:
(df1 == df2).all()

review    True
dtype: bool

ドキュメントをトークン化

In [204]:
def tokenizer(text):
    return text.split()

tokenizer('runners like running and thus they run')

['runners', 'like', 'running', 'and', 'thus', 'they', 'run']

In [205]:
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()
def tokenizer_porter(text):
    return [porter.stem(word) for word in text.split()]

tokenizer_porter('runners like running and thus they run')

['runner', 'like', 'run', 'and', 'thu', 'they', 'run']

In [208]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/keeeeei/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [215]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
[w for w in tokenizer_porter('a runner likes running and runs a lot')[-10:]
      if w not in stop]

['runner', 'like', 'run', 'run', 'lot']

ドキュメントを分類するロジスティック回帰モデルのトレーニング

In [216]:
X_train = df.loc[:25000, 'review'].values
y_train = df.loc[:25000, 'sentiment'].values
X_test = df.loc[25000:, 'review'].values
y_test = df.loc[25000:, 'sentiment'].values

In [241]:
from sklearn.grid_search import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(strip_accents=None,#アクセント(口調、言葉使い)(解析上邪魔なもの)を取り除くか、方法としてはasciiやunicode
                                        lowercase = False,　#全て小文字にするか
                                        preprocessor=None)　#読み込んだドキュメントを加工する方法(例えば全部大文字にする関数などが入る)
param_grid = [{'vect__ngram_range': [(1,1)],
                            'vect__stop_words': [stop, None],
                            'vect__tokenizer': [tokenizer, tokenizer_porter], #tokenizerは空白で区切る。tokenizer_porterは空白で区切り動詞を原形にする
                            'clf__penalty': ['l1', 'l2'],
                            'clf__C': [1.0, 10.0, 100.0]},
                          {'vect__ngram_range': [(1,1)],
                            'vect__stop_words': [stop, None],
                            'vect__tokenizer': [tokenizer, tokenizer_porter],
                            'vect__use_idf': [False],　#idfを使用しない
                            'vect__norm':[None],　　　　　　#正規化を行わない(default:l2)  →この二つより生の単語の出現回数でトレーニングする
                            'clf__penalty': ['l1', 'l2'],
                            'clf__C': [1.0, 10.0, 100.0]},]

lr_tfidf = Pipeline([('vect', tfidf),
                                 ('clf', LogisticRegression(random_state=0))])
gs_lr_tfidf = GridSearchCV(estimator=lr_tfidf,
                                                param_grid=param_grid,
                                                scoring='accuracy',
                                                cv=5,
                                                verbose=1,#一定間隔でログを表示
                                                n_jobs=-1)

gs_lr_tfidf.fit(X_train, y_train)


Fitting 5 folds for each of 48 candidates, totalling 240 fits


[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed: 10.2min
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed: 52.5min
[Parallel(n_jobs=-1)]: Done 240 out of 240 | elapsed: 68.0min finished


GridSearchCV(cv=5, error_score='raise',
       estimator=Pipeline(steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=False, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
 ...nalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))]),
       fit_params={}, iid=True, n_jobs=-1,
       param_grid=[{'vect__ngram_range': [(1, 1)], 'clf__penalty': ['l1', 'l2'], 'clf__C': [1.0, 10.0, 100.0], 'vect__stop_words': [['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'hers', 'herself',...x13345ae18>], 'clf__C': [1.0, 10.0, 100.0], 'clf__penalty': ['l1', 'l2'], 'vect__use_idf': [False]}],
       pre_dispatch='2*n_jobs', refit=True, scoring='accuracy', verbose=1

In [242]:
print('Best parameter set: %s' % gs_lr_tfidf.best_params_)

Best parameter set: {'clf__C': 10.0, 'clf__penalty': 'l2', 'vect__ngram_range': (1, 1), 'vect__stop_words': None, 'vect__tokenizer': <function tokenizer at 0x132071d90>}


In [251]:
print('CV Accuracy: %.3f' % gs_lr_tfidf.best_score_)
clf = gs_lr_tfidf.best_estimator_
print('Test Accuracy: %.3f' % clf.score(X_test, y_test))

CV Accuracy: 0.897
Test Accuracy: 0.899


In [252]:
print('CV Accuracy: %.3f' % gs_lr_tfidf.best_score_)
clf = gs_lr_tfidf.best_estimator_
print('Test Accuracy: %.3f' % clf.score(X_test, y_test))

CV Accuracy: 0.897
Test Accuracy: 0.899


In [248]:
##引数preprocessorの使い方
def preProcess(s):
    return s.upper()

corpus = [
     'This is the first document.',
     'This is the second second document.',
     'And the third one.',
     'Is this the first document?'
     ]

X = TfidfVectorizer(preprocessor=preProcess)
X.fit(corpus)
X.get_feature_names()



['AND', 'DOCUMENT', 'FIRST', 'IS', 'ONE', 'SECOND', 'THE', 'THIRD', 'THIS']

オンラインアルゴリズムとアウトオブコア学習

In [257]:
import re
from nltk.corpus import stopwords
stop = stopwords.words('english')
#顔文字は残し余計な表現は捨て、さらにstopwordsに含まれるものも捨て、空白でトークン化
def tokenizer(text):
    text= re.sub('<[^>]*>', '', text)
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|d|p)',text.lower())
    text = re.sub('[\W]+', ' ', text.lower()) + ' '.join(emoticons).replace('-', '')
    tokenized = [w for w in text.split() if w not in stop]
    return tokenized

In [264]:
#各行の文章と正解データを抽出
def stream_docs(path):
    with open(path, 'r', encoding='utf-8') as csv:
        next(csv) #ヘッダーを読み飛ばす
        for line in csv:
            text, label = line[:-3], int(line[-2])
            yield text, label

In [291]:
type(next(stream_docs(path='movie_data.csv')))

tuple

In [269]:
df.head()

review  sentiment
0  in 1974 the teenager martha moxley maggie grac...          1
1  ok so i really like kris kristofferson and his...          0
2   spoiler do not read this if you think about w...          0
3  hi for all the people who have seen this wonde...          1
4  i recently bought the dvd forgetting just how ...          0

In [271]:
df.head(1)

review  sentiment
0  in 1974 the teenager martha moxley maggie grac...          1

In [290]:
#文章と正解が入ったタプルからsizeのぶんだけ抜き出す
def get_minibatch(doc_stream, size):
    docs, y = [], []
    #try,exceptはtryを実行してエラーが出たらexceptを実行する
    try:
        for _ in range(size):
            text, label = next(doc_stream)
            docs.append(text)
            y.append(label)
    except StopIteration:
        return None, None
    return docs, y

In [275]:
with open('movie_data.csv', 'r', encoding='utf-8') as csv:
        print(next(csv)) #ヘッダーを読み飛ばす
        print(next(csv))

review,sentiment

"In 1974, the teenager Martha Moxley (Maggie Grace) moves to the high-class area of Belle Haven, Greenwich, Connecticut. On the Mischief Night, eve of Halloween, she was murdered in the backyard of her house and her murder remained unsolved. Twenty-two years later, the writer Mark Fuhrman (Christopher Meloni), who is a former LA detective that has fallen in disgrace for perjury in O.J. Simpson trial and moved to Idaho, decides to investigate the case with his partner Stephen Weeks (Andrew Mitchell) with the purpose of writing a book. The locals squirm and do not welcome them, but with the support of the retired detective Steve Carroll (Robert Forster) that was in charge of the investigation in the 70's, they discover the criminal and a net of power and money to cover the murder.<br /><br />""Murder in Greenwich"" is a good TV movie, with the true story of a murder of a fifteen years old girl that was committed by a wealthy teenager whose mother was a Kennedy. The powe

In [279]:
with open('movie_data.csv', 'r', encoding='utf-8') as csv:
        txt = csv.read()

In [289]:
with open('movie_data.csv', 'r', encoding='utf-8') as csv:
    next(csv) #ヘッダーを読み飛ばす
    for line in csv:
        print(line[-2])
        if True:
            break

1


In [300]:
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.linear_model import SGDClassifier
#decode_errorはエンコーディングの文字列と違ったものが含まれた時にどうするか
#n_featuresはハッシュ値の個数
vect = HashingVectorizer(decode_error='ignore',
                        n_features = 2**21,
                        preprocessor=None,
                        tokenizer=tokenizer)
clf = SGDClassifier(loss='log', random_state=1, n_iter=1)
doc_stream = stream_docs(path='movie_data.csv')

In [301]:
doc_stream

<generator object stream_docs at 0x135c390a0>

In [302]:
pbar = pyprind.ProgBar(45)
classes = np.array([0,1])
#X_trainが空の時はNoneを返すようにget_minibatchで設定済
for _ in range(45):
    X_train, y_train = get_minibatch(doc_stream, size=1000)
    if not X_train:
        break
    X_train = vect.transform(X_train)
    clf.partial_fit(X_train, y_train, classes=classes)
    pbar.update()

0%                          100%
[##############################] | ETA: 00:00:00
Total time elapsed: 00:00:38


In [303]:
r = None
not r

True

In [304]:
X_test, y_test = get_minibatch(doc_stream,size=5000)
X_test = vect.transform(X_test)
print('Accuracy: %.3f' % clf.score(X_test, y_test))

Accuracy: 0.867


In [305]:
clf = clf.partial_fit(X_test, y_test)